### ISSUE TITLE
插件安装报错

### ISSUE THREAD

**Issue by MIyulong** [dtlnor/stable-diffusion-webui-localization-zh_CN#23]
插件安装时报错，尝试安装其他插件可以安装运行
*** Error completing request
*** Arguments: ('https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN', ['ads'], 0, '') {}
    Traceback (most recent call last):
      File "/Users/xxx/Desktop/stable-diffusion-webui/modules/call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "/Users/xxx/Desktop/stable-diffusion-webui/modules/ui_extensions.py", line 384, in install_extension_from_index
        ext_table, message = install_extension_from_url(None, url)
      File "/Users/xxx/Desktop/stable-diffusion-webui/modules/ui_extensions.py", line 354, in install_extension_from_url
        with git.Repo.clone_from(url, tmpdir, filter=['blob:none']) as repo:

这是我的版本信息
<img width="654" alt="image" src="https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN/assets/8175565/e101c0b9-7c5b-4170-acd1-faae77b368e6">

**Comment by dtlnor** [comment]
![image](https://github.com/dtlnor/stable-diffusion-webui-localization-zh_CN/assets/21131439/b4a2ab72-f2b8-4854-ab75-c6898f87dbf3)
我这边测试全新下载的sdwebui没有问题。会不会是网络问题或者是路径问题？
